### ISSUE TITLE
[Bug]: Crater Example docker-compose.yml not working

### ISSUE THREAD

**Issue by natterstefan** [shinsenter/php#21]
## Issue description

I get multiple errors when starting the docker image with the given example compose file.

## Environment

- Opertaing System Version: macos
- Docker Version: 20.10.21

## Steps to reproduce the issue

1. Take my `docker-compose.yml` and start it with `docker-compose up`. Attention: I used different ports for crater and myql, and the network part is taken from [crater's docker-compose example](https://github.com/crater-invoice/crater/blob/393fe20010d4ddbc4eb49e739000f55d8d7e0b8b/docker-compose.yml#L17-L18).

```yml
version: '3'

services:
  crater:
    # do not update until https://github.com/shinsenter/php/issues/18#issuecomment-1366262015 is fixed
    image: shinsenter/crater:php8.1
    restart: always
    volumes:
      - ./volumes/crater:/var/www/html:rw
      # - ./ssl-certs:/etc/ssl/web
    environment:
      TZ: Europe/Vienna
      PUID: ${UID:-9999}
      PGID: ${GID:-9999}
      # REDIS_HOST: redis
      DB_HOST: mysql
      DB_DATABASE: crater
      DB_USERNAME: root
      DB_PASSWORD: mydb_p@ssw0rd
      # CRATER_QUEUE_ENABLED: true
      # CRATER_QUEUE_OPTIONS: --timeout=60 --tries=3 redis
      # CRATER_SCHEDULE_ENABLED: true
    ports:
      - "3050:80"
      # - "443:443"
    links:
      - mysql
      # - redis
    networks:
      - crater

  mysql:
    image: mysql:8.0.32
    restart: always
    environment:
      TZ: Europe/Vienna
      MYSQL_ROOT_PASSWORD: mydb_p@ssw0rd
      MYSQL_DATABASE: crater
    volumes:
      - "./volumes/mysql/data:/var/lib/mysql"
      # - "./volumes/mysql/dump:/docker-entrypoint-initdb.d"
    ports:
      - "3060:3306"
    networks:
      - crater

  # redis:
  #   image: redis:7.0.8-alpine
  #   ports:
  #     - "6379:6379"

networks:
  crater:
    driver: bridge
```

## What is expected?

- Setup and Installation works (e.g. database connection info is taken from ENV variables)

## Additional details / screenshots

- Related issues: https://github.com/shinsenter/php/issues/11

### Screenshots

Not sure why this is happening at the moment
<img width="1565" alt="image" src="https://user-images.githubusercontent.com/1043668/213100913-c5a12cf8-610d-4352-8c11-95a38d950be6.png">

Values are not taken from the compose file as expected
<img width="1563" alt="image" src="https://user-images.githubusercontent.com/1043668/213100960-e203b162-a387-4aaf-85bd-da335c78e1c0.png">

The port is not taken from the compose file, which leads to an error as expected
<img width="1658" alt="image" src="https://user-images.githubusercontent.com/1043668/213101033-d2a7ce85-2f66-4ba5-b2b2-c059dd9f0316.png">

Even when I change the port to the one in the compose file it does not work:

<img width="1641" alt="image" src="https://user-images.githubusercontent.com/1043668/213101151-527909a5-2504-4c90-bd7a-e4231e746510.png">

**Comment by shinsenter** [comment]
@natterstefan 

I deeply apologize for any inconvenience that may have been caused to you.
After reviewing your docker-compose.yml file, I believe it is in proper working order.
Unfortunately, connection errors have occurred during the installation of Crater in your specific case.

Without delving into the specific details of the source code or error logs, it is challenging to pinpoint the exact issue.
I will take time to thoroughly investigate and determine a solution. But if you have any suggestions or insights, please do not hesitate to share them with me as I am eager to improve the process for you and others.

Lastly, I would like to emphasize that these docker images are simply pre-built environments that provide the necessary services for launching websites created with Crater. Please note that these images do not include the Crater source code, but rather a small script that enables you to easily pull the latest source code from Packagist.

Best regrads

**Comment by shinsenter** [comment]
@natterstefan 

After taking a quick look at the Crater source code, I found that the default installation configuration may be hard-coded in this file. This means that it doesn't seem to be pulling values from environment variables.

https://github.com/crater-invoice/crater/blob/393fe20010d4ddbc4eb49e739000f55d8d7e0b8b/app/Http/Controllers/V1/Installation/DatabaseConfigurationController.php#L71-L76

**Comment by shinsenter** [comment]
@natterstefan 

Based on my understanding, I believe that the mysql port in the installation screen should be set to 3306.
This is because the containers are communicating with each other on the internal network using their exposed ports.

When you changed the mysql port from 3306 to 3060 in your docker-compose.yml file, it means that you allow access to the mysql container via the port 3060, both from from outside the docker network or from your host machine.

**Comment by natterstefan** [comment]
Hi @shinsenter,

> I deeply apologize for any inconvenience that may have been caused to you.

No worries at all. Things like this can happen from time to time. Thanks for your response.

Meanwhile, I fixed the connection issue to the database, after using `mariadb` as stated in the example compose of crater: https://github.com/crater-invoice/crater/blob/393fe20010d4ddbc4eb49e739000f55d8d7e0b8b/docker-compose.yml#L20-L37.

I also used the connection settings mentioned [here](https://docs.craterapp.com/installation.html#step-5-complete-installation-wizard):

- Database Host: `db`
- Database Name: `crater`
- Database Username: `crater`
- Database Password: `crater`

I am facing another issue now that is probably not related to your setup and image: https://github.com/crater-invoice/crater/issues/1117#issuecomment-1396455648. Do you know something about this?

I will close this issue until I find out what to do next.

Thanks for your help!

**Comment by d9media** [comment]
> Hi @shinsenter,
> 
> > I deeply apologize for any inconvenience that may have been caused to you.
> 
> No worries at all. Things like this can happen from time to time. Thanks for your response.
> 
> Meanwhile, I fixed the connection issue to the database, after using `mariadb` as stated in the example compose of crater: https://github.com/crater-invoice/crater/blob/393fe20010d4ddbc4eb49e739000f55d8d7e0b8b/docker-compose.yml#L20-L37.
> 
> I also used the connection settings mentioned [here](https://docs.craterapp.com/installation.html#step-5-complete-installation-wizard):
> 
> * Database Host: `db`
> * Database Name: `crater`
> * Database Username: `crater`
> * Database Password: `crater`
> 
> I am facing another issue now that is probably not related to your setup and image: [crater-invoice/crater#1117 (comment)](https://github.com/crater-invoice/crater/issues/1117#issuecomment-1396455648). Do you know something about this?
> 
> I will close this issue until I find out what to do next.
> 
> Thanks for your help!

I changed the values to represent your suggestions but I still get
` *25 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot declare class CreateBouncerTables, because the name is already in use in /var/www/html/database/migrations/2023_01_30_055655_create_bouncer_tables.php on line 0" while reading response header from upstream`

**Comment by d9media** [comment]
Okay so when you look at that folder you can see the problem:

![image](https://user-images.githubusercontent.com/3267515/215402555-364d3e3d-120a-4e64-a03e-2d9faf357d7b.png)

I deleted the two migration php files in conflict (creater_bouncer_tables.php). After that, the same error occured with createMediaTable so I removed those as well. Then it worked.

**Comment by shinsenter** [comment]
@d9media 

I think the issue you're facing has to do with the migration logic of the Crater framework, as our Docker images don't include the source code for Crater, which may be causing the problem.

You can check out the issue at [crater-invoice/crater#1117](https://github.com/crater-invoice/crater/issues/1117) and wait for the Crater developers to come up with a solution.

I'll also have a look and see if I can find a way to resolve it. If you have any suggestions, I'd love to hear them to try and improve the situation with the Docker images.

Best regards

**Comment by shinsenter** [comment]
@natterstefan @d9media 

After reviewing the Crater installation process, I discovered that two dependencies were causing issues.
They will generate their own migration scripts when Crater saving the database connection settings.

https://github.com/spatie/laravel-medialibrary/blob/067a3710096fec4e5ed193031803cc5b91e476f5/src/MediaLibraryServiceProvider.php#L47-L51

https://github.com/JosephSilber/bouncer/blob/2c08082f0e4d13fcdc11ceb020badf272c05faa6/src/BouncerServiceProvider.php#L100-L113

I think this issue needs to be reviewed by Crater's developers and they would provide a fix soon.

**Comment by shinsenter** [comment]
@natterstefan @d9media 

I have improved the behavior of the init script inside the Crater container.

Please check the latest build of the docker image at https://docker.shin.company/crater

If you have any questions or concerns about the source code or anything else, please let me know and I'll be happy to help.

**Comment by d9media** [comment]
Thank you so much for your dedication and quick response @shinsenter! For the time being, I solved the issue by removing the duplicate files. I was just gonna test-drive the solution but it I'm not entirely sure I will settle for it. Should I decide to you use it, I will happily report back. Maybe natterstefan could find it useful too. Thanks!
